---
system:
  lite: false

plugins:
  probe_spec: dan,encoding,glitch,goodside,av_spam_scanning,leakreplay,malwaregen,misleading,packagehallucination,promptinject,snowball,xss
  probes:
    encoding:
      payloads:
        - default
        - xss
